//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace LMWebApp.pg {
    
    
    public partial class policyTab4ImplModal {
        
        /// <summary>
        /// policyTab4ImplModalHeaderLabel control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalHeaderLabel;
        
        /// <summary>
        /// policyTab4ImplModalID control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalID;
        
        /// <summary>
        /// policyTab4ImplModalCurrentYr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalCurrentYr;
        
        /// <summary>
        /// policyTab4ImplModalCurrentYrhf control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalCurrentYrhf;
        
        /// <summary>
        /// policyTab4ImplModalCharLength control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalCharLength;
        
        /// <summary>
        /// policyTab4ImplModalDivPlanyrImplImport control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl policyTab4ImplModalDivPlanyrImplImport;
        
        /// <summary>
        /// policyTab4ImplModalImpl control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlTextArea policyTab4ImplModalImpl;
        
        /// <summary>
        /// policyTab4ImplModalAttachBtn control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor policyTab4ImplModalAttachBtn;
        
        /// <summary>
        /// policyTab4ImplModalAttachInput control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputFile policyTab4ImplModalAttachInput;
    }
}
